<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>Latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\YMplugins.Contracts\YMplugins.Contracts.csproj" />
    <ProjectReference Include="..\YMplugins.Settings\YMplugins.Settings.csproj" />
  </ItemGroup>

</Project>
