<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
	  <LangVersion>preview</LangVersion>
	  <Configurations>Debug;Release;Autocad;Test</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ViewModels\YMplugins.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System.Numerics">
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System.Xaml">
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
