<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;Release;Autocad;Test</Configurations>

  </PropertyGroup>

  <ItemGroup>
    <None Remove="Icons\autoprint.png" />
    <None Remove="Icons\translation.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SimpleInjector" Version="5.5.0"/>
    <PackageReference Include="AutoCAD.NET" Version="24.3.0" ExcludeAssets="runtime"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Models\YMplugins.Models.Autocad2022\YMplugins.Models.Autocad2022.csproj" />
    <ProjectReference Include="..\..\ViewModels\YMplugins.ViewModels.csproj" />
    <ProjectReference Include="..\..\Views\WPF\YMplugins.Views.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Gile.AutoCAD.Extension">
      <HintPath>D:\from comp\docs\repos\TransmittalCreator\TransmittalCreator\bin\Debug\Gile.AutoCAD.Extension.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="PresentationCore">
      <Private>False</Private>
    </Reference>
    <Reference Include="PresentationFramework">
      <Private>False</Private>
    </Reference>
    <Reference Include="WindowsBase">
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icons\autoprint.png" />
    <Resource Include="Icons\translation.png" />
  </ItemGroup>

</Project>
