<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Icons\translation.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoCAD.NET.Interfaces" Version="24.4.20296.1" />
    <PackageReference Include="SimpleInjector" Version="5.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Models\YMplugins.Models.Autocad2022\YMplugins.Models.Autocad2022.csproj" />
    <ProjectReference Include="..\..\ViewModels\YMplugins.ViewModels.csproj" />
    <ProjectReference Include="..\..\Views\WPF\YMplugins.Views.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icons\translation.png" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /y /r &quot;$(TargetDir)*.dll&quot; &quot;%25appdata%25\Autodesk\ApplicationPlugins\YMplugins.bundle\Contents\&quot;" />
  </Target>

</Project>
