<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Autocad;Test</Configurations>
    <Platforms>AnyCPU;ARM32</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext7" Version="8.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Models\YMplugins.Models.Autocad2024\YMplugins.Models.Autocad2024.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PiaNO">
      <HintPath>..\..\..\..\..\Documents\PiaNO-patch-1\PiaNO-patch-1\bin\Debug\PiaNO.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
