<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoCAD.NET.Interfaces" Version="24.4.20296.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Services\YMplugins.Services\YMplugins.Services.csproj" />
    <ProjectReference Include="..\..\ViewModels\YMplugins.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AutoCADCommands">
      <HintPath>D:\sharp\Projects for learning\AcadLibs\AutoCADCodePack\bin\r23\AutoCADCommands.dll</HintPath>
    </Reference>
    <Reference Include="Gile.AutoCAD.Extension">
      <HintPath>D:\from comp\docs\repos\TransmittalCreator\TransmittalCreator\bin\Debug\Gile.AutoCAD.Extension.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
