<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;Release;Autocad;Test</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoCAD.NET" Version="24.3.0" ExcludeAssets="runtime"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\external\Gile.AutoCAD.Extension\Gile.AutoCAD.R20.Extension\Gile.AutoCAD.R20.Extension.csproj" />
  </ItemGroup>
</Project>
